version: "3.5"

services:
  api1: &api
    container_name: api1
    # image: zecs/api-insana-do-rei-zeca:latest
    build: .
    hostname: api1
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=db
    # ports:
    #   - "8001:8000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200MB"

  api2:
    <<: *api
    container_name: api2
    hostname: api2
    # ports:
    #   - "8002:8000"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    # ports:
    #   - "5432:5432"
    volumes:
      - ./scriptsql:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "140MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"
# networks:
#   default:
#     driver: bridge
#     name: rinha-nginx-2024q1
