version: "3.5"

services:
  api01: &api
    image: zecs/api-insana-do-rei-zeca:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
  
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "200MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./scriptsql:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "140MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "10MB"